import { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  es: {
    // Header
    archive: 'Archivo',
    scriptorium: 'Scriptorium',
    myProfile: 'Mi perfil',
    logout: 'Cerrar sesión',
    confirmLogoutMessage: '¿Estás seguro de que quieres cerrar sesión?',
    confirmLogoutConfirm: 'Sí, cerrar sesión',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    home: 'Inicio',
    welcome: 'Bienvenido',
    menu: 'Menú',
    firstTimeHere: '¿Necesitas ayuda?\nPulsa ? para ver cómo funciona esta sección',
    
    // Login
    loginTitle: '📜 La voz de las páginas',
    loginSubtitle: 'Inicia sesión para continuar tu aventura',
    usernameOrEmail: 'Usuario o Email',
    password: 'Contraseña',
    loginButton: 'Iniciar Sesión',
    loggingIn: 'Iniciando sesión...',
    noAccount: '¿No tienes cuenta?',
    registerHere: 'Regístrate aquí',
    loginError: 'Error al iniciar sesión. Por favor, intenta de nuevo.',
    invalidCredentials: 'Credenciales inválidas',
    
    // Register
    registerTitle: '📜 Registro',
    registerSubtitle: 'Crea tu cuenta para empezar a escribir',
    username: 'Nombre de Usuario',
    email: 'Email',
    confirmPassword: 'Confirmar Contraseña',
    registerButton: 'Registrarse',
    registering: 'Registrando...',
    hasAccount: '¿Ya tienes cuenta?',
    loginHere: 'Inicia sesión aquí',
    usernameHint: 'Entre 3 y 20 caracteres, solo letras, números, guiones y guiones bajos.',
    passwordsNoMatch: 'Las contraseñas no coinciden.',
    registerError: 'Error al registrar usuario. Por favor, intenta de nuevo.',
    emailAlreadyExists: 'El email ya está registrado',
    usernameAlreadyExists: 'El nombre de usuario ya está en uso',
    invalidEmailFormat: 'El formato del email no es válido',
    invalidUsernameFormat: 'El nombre de usuario debe tener entre 3 y 20 caracteres y solo puede contener letras, números, guiones y guiones bajos',
    allFieldsRequired: 'Todos los campos son requeridos',
    checkEmailToVerify: 'Revisa tu correo: te hemos enviado un enlace para verificar tu cuenta.',
    checkEmailForCode: 'Te hemos enviado un código de 6 dígitos a tu correo. Introdúcelo en la web para verificar tu cuenta.',
    enterCodeHere: 'Introducir el código',
    enterVerificationCode: 'Introduce el código que te hemos enviado por correo.',
    verificationCodeLabel: 'Código de verificación',
    verificationCodePlaceholder: '000000',
    verifyButton: 'Confirmar',
    resendCodeButton: 'Reenviar el código',
    codeMustBe6Digits: 'El código debe tener 6 dígitos.',
    noCodeReceived: '¿No te ha llegado el código?',
    andResendCode: 'Inicia sesión y podrás solicitar uno nuevo.',
    verificationSuccess: 'Correo verificado correctamente.',
    verificationCompleteMessage: 'Verificación completada. Ya puedes iniciar sesión.',
    verificationAlreadyVerified: 'Tu cuenta ya está verificada; puedes iniciar sesión.',
    emailNotVerified: 'Debes verificar tu correo electrónico para acceder.',
    resendVerificationLabel: 'Reenviar correo de verificación:',
    resendVerificationButton: 'Reenviar correo',
    verificationEmailSent: 'Se ha enviado un nuevo correo de verificación.',
    sending: 'Enviando...',
    verificationTitle: 'Verificación de correo',
    verifying: 'Verificando...',
    verificationFailed: 'No se pudo verificar el correo. El enlace puede haber caducado.',
    verificationAlreadyUsed: 'Este enlace ya fue utilizado. Tu cuenta ya está verificada; puedes iniciar sesión.',
    verificationTokenMissing: 'Falta el enlace de verificación.',
    goToLogin: 'Ir a iniciar sesión',
    
    // Home
    welcomeTitle: 'La voz de las páginas',
    welcomeP1: 'Aquí, donde la imaginación deja de ser un susurro y se convierte en palabra escrita, nacen los mundos que aún no existen y respiran los personajes que esperan ser recordados. Este no es solo un lugar para contar historias: es un refugio para narradores, un taller para arquitectos de tramas, un archivo vivo donde cada idea encuentra forma, orden y propósito.',
    welcomeP2: 'En La voz de las páginas, tus relatos no existen en soledad. Este es un espacio concebido para que tus ideas encuentren forma, profundidad y coherencia, permitiéndote desarrollar historias que respiran y evolucionan con naturalidad. Ya escribas fantasía, ciencia ficción, drama o crónicas de mundos imposibles, aquí tus narraciones crecen, se consolidan y se preparan para ser compartidas con otros, dentro de un universo que respeta y potencia tu visión creativa.',
    welcomeP3: 'Cruza el umbral. Escribe. Construye. Da voz a las páginas.',
    
    // Profile
    profileTitle: 'Mi Perfil',
    memberSince: 'Miembro desde',
    profileImage: 'Imagen de perfil',
    changeProfileImage: 'Cambiar imagen de perfil',
    clickToChangeImage: 'Haz clic para cambiar la imagen',
    invalidImageType: 'Tipo de archivo no válido. Solo se permiten imágenes.',
    imageTooLarge: 'La imagen es demasiado grande (máximo 2MB)',
    uploadError: 'Error al subir la imagen',
    
    // Change Password
    changePassword: 'Cambiar Contraseña',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmNewPassword: 'Confirmar Nueva Contraseña',
    passwordChanged: 'Contraseña actualizada exitosamente',
    passwordChangeError: 'Error al cambiar la contraseña',
    currentPasswordIncorrect: 'La contraseña actual es incorrecta',
    newPasswordsDontMatch: 'Las contraseñas nuevas no coinciden',
    samePasswordError: 'La nueva contraseña debe ser diferente a la actual',
    
    // Scriptorium
    scriptoriumWelcome: 'Bienvenido al Scriptorium',
    stories: 'Historias',
    storiesDescription: 'Crea y gestiona tus relatos. Desde cuentos cortos hasta sagas épicas, organiza todas tus narraciones en un solo lugar.',
    characters: 'Personajes',
    charactersDescription: 'Da vida a tus protagonistas y antagonistas. Define sus rasgos, motivaciones y arcos de desarrollo.',
    plots: 'Líneas temporales',
    plotsDescription: 'Gestiona las líneas temporales de tus historias. Organiza eventos, tramas y notas.',
    
    // Plots/Timelines Page
    timelines: 'Líneas Temporales',
    plot: 'trama',
    errorLoadingTimelines: 'Error al cargar las líneas temporales',
    noTimelinesYet: 'Aún no tienes líneas temporales',
    createStoryForTimeline: 'Crea una historia para generar una línea temporal',
    allStories: 'Todas las historias',
    noTimelinesForThisStory: 'No hay líneas temporales para esta historia',
    selectAnotherStoryOrCreate: 'Selecciona otra historia o crea una nueva línea temporal',
    newTimeline: 'Nueva línea temporal',
    timelineName: 'Nombre de la línea temporal',
    timelineNamePlaceholder: 'Ej: Línea temporal principal',
    story: 'Historia',
    selectStory: 'Seleccionar historia',
    storyRequired: 'Debes seleccionar una historia',
    errorCreatingTimeline: 'Error al crear la línea temporal',
    confirmDeleteTimeline: '¿Eliminar esta línea temporal?',
    deleteTimelineConfirmMessage: 'Se eliminará la línea temporal «{name}» y todas sus tramas. Esta acción no se puede deshacer.',
    errorDeletingTimeline: 'Error al eliminar la línea temporal',
    errorLoadingTimeline: 'Error al cargar la línea temporal',
    timelineNotFound: 'Línea temporal no encontrada',
    backToTimelines: 'Volver a líneas temporales',
    tramas: 'Tramas',
    noPlotsYet: 'Aún no hay tramas',
    addPlotsToTimeline: 'Añade tramas a esta línea temporal',
    chapter: 'Cap.',
    chapters: 'capítulos',
    chapterSingular: 'capítulo',
    addChapter: 'Añadir capítulo',
    removeChapter: 'Eliminar capítulo',
    newPlot: 'Nueva trama',
    plotName: 'Nombre de la trama',
    plotNamePlaceholder: 'Ej: Romance principal',
    startChapter: 'Capítulo inicial',
    endChapter: 'Capítulo final',
    plotNameRequired: 'El nombre de la trama es requerido',
    startCantBeGreaterThanEnd: 'El inicio no puede ser mayor que el final',
    errorCreatingPlot: 'Error al crear la trama',
    creating: 'Creando...',
    errorUpdatingPlot: 'Error al actualizar la trama',
    plotDescription: 'Descripción',
    plotDescriptionPlaceholder: 'Descripción opcional de la trama',
    plotColor: 'Color',
    editPlot: 'Editar trama',
    highlightOnTimeline: 'Resaltar en la línea temporal',
    savePlot: 'Guardar',
    confirmDeletePlot: '¿Eliminar esta trama?',
    deletePlotConfirmMessage: 'Se eliminará la trama «{name}». Esta acción no se puede deshacer.',
    deletePlotWarning: 'Esta acción no se puede deshacer.',
    errorDeletingPlot: 'Error al eliminar la trama',
    deleting: 'Eliminando...',
    notes: 'Notas',
    note: 'nota',
    newNote: 'Nueva nota',
    noteName: 'Nombre de la nota',
    noteNamePlaceholder: 'Ej: Suceso clave',
    notePosition: 'Posición (capítulo)',
    noteNameRequired: 'El nombre de la nota es requerido',
    noNotesYet: 'Aún no hay notas',
    addNotesToTimeline: 'Añade notas en un punto concreto',
    editNote: 'Editar nota',
    confirmDeleteNote: '¿Eliminar esta nota?',
    deleteNoteConfirmMessage: 'Se eliminará la nota «{name}».',
    errorCreatingNote: 'Error al crear la nota',
    errorUpdatingNote: 'Error al actualizar la nota',
    errorDeletingNote: 'Error al eliminar la nota',
    
    // Stories Page
    myStories: 'Mis Historias',
    newStory: 'Nueva Historia',
    createNewStory: 'Crear Nueva Historia',
    storyTitle: 'Título',
    storyTitlePlaceholder: 'El título de tu historia...',
    storyContent: 'Contenido',
    storyContentPlaceholder: 'Escribe tu historia aquí...',
    visibility: 'Visibilidad',
    public: 'Público',
    private: 'Privado',
    unlisted: 'No listado',
    create: 'Crear',
    noStoriesYet: 'Aún no tienes historias',
    createFirstStory: 'Crea tu primera historia y comienza a escribir',
    errorLoadingStories: 'Error al cargar las historias',
    errorCreatingStory: 'Error al crear la historia',
    errorDeletingStory: 'Error al eliminar la historia',
    confirmDelete: '¿Eliminar historia?',
    deleteStoryWarning: 'Esta acción no se puede deshacer. Se eliminará permanentemente:',
    delete: 'Eliminar',
    
    // Story Editor
    errorLoadingStory: 'Error al cargar la historia',
    editStory: 'Editar historia',
    noCharactersYet: 'Aún no hay personajes',
    noChaptersYet: 'Aún no hay capítulos',
    addCharacter: 'Añadir personaje',
    newCharacter: 'Nuevo personaje',
    characterName: 'Nombre',
    characterDescription: 'Descripción',
    editCharacter: 'Editar personaje',
    confirmDeleteCharacter: '¿Eliminar este personaje?',
    newChapter: 'Nuevo capítulo',
    chapterTitle: 'Título',
    chapterOrder: 'Orden',
    editChapter: 'Editar capítulo',
    confirmDeleteChapter: '¿Eliminar este capítulo?',
    editChapterContent: 'Editar texto',
    storyTextInChapters: 'El texto de la historia se escribe en cada capítulo.',
    manageChaptersAndContent: 'Gestionar capítulos y contenido',
    errorSavingStory: 'Error al guardar la historia',
    backToStories: 'Volver a historias',
    saving: 'Guardando...',
    saved: 'Guardado',
    unsaved: 'Sin guardar',
    untitledStory: 'Historia sin título',
    settings: 'Configuración',
    startWriting: 'Comienza a escribir tu historia...',
    words: 'palabras',
    chars: 'caracteres',
    save: 'Guardar',
    addSeparator: 'Añadir separador',
    separatorDefaultLabel: 'Separador',
    
    // Formatting Toolbar
    paragraph: 'Párrafo',
    heading: 'Título',
    bold: 'Negrita',
    italic: 'Cursiva',
    underline: 'Subrayado',
    strikethrough: 'Tachado',
    bulletList: 'Lista con viñetas',
    numberedList: 'Lista numerada',
    quote: 'Cita',
    alignLeft: 'Alinear a la izquierda',
    alignCenter: 'Centrar',
    alignRight: 'Alinear a la derecha',
    alignJustify: 'Justificar',
    
    // Common
    loading: 'Cargando...',
    back: 'Volver',
    cancel: 'Cancelar',
    close: 'Cerrar',
    quickAccess: 'Acceso rápido',
    navigation: 'Navegación',
    account: 'Cuenta',

    // Tutorial
    tutorialNext: 'Siguiente',
    tutorialPrev: 'Anterior',
    tutorialHomeScriptoriumTitle: 'Scriptorium',
    tutorialHomeScriptoriumBody: 'Tu espacio de trabajo. Desde aquí accedes a Historias, Personajes y Líneas temporales para organizar tus proyectos narrativos.',
    tutorialHomeArchiveTitle: 'Archivo',
    tutorialHomeArchiveBody: 'El archivo te permitirá guardar y consultar contenido. Esta función estará disponible próximamente.',
    tutorialHomeMenuTitle: 'Menú desplegable',
    tutorialHomeMenuBody: 'En la esquina superior derecha del header encontrarás el menú: Inicio, Mi perfil, idioma y tema. Úsalo para navegar y configurar la aplicación.',
  },
  en: {
    // Header
    archive: 'Archive',
    scriptorium: 'Scriptorium',
    myProfile: 'My Profile',
    logout: 'Log out',
    confirmLogoutMessage: 'Are you sure you want to log out?',
    confirmLogoutConfirm: 'Yes, log out',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    home: 'Home',
    welcome: 'Welcome',
    menu: 'Menu',
    firstTimeHere: 'Need help?\nPress ? to see how this section works.',
    languageLabel: 'Language',
    
    // Login
    loginTitle: '📜 The voice within the pages',
    loginSubtitle: 'Log in to continue your adventure',
    usernameOrEmail: 'Username or Email',
    password: 'Password',
    loginButton: 'Log In',
    loggingIn: 'Logging in...',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    loginError: 'Login error. Please try again.',
    invalidCredentials: 'Invalid credentials',
    
    // Register
    registerTitle: '📜 Register',
    registerSubtitle: 'Create your account to start writing',
    username: 'Username',
    email: 'Email',
    confirmPassword: 'Confirm Password',
    registerButton: 'Register',
    registering: 'Registering...',
    hasAccount: 'Already have an account?',
    loginHere: 'Log in here',
    usernameHint: 'Between 3 and 20 characters, only letters, numbers, hyphens and underscores.',
    passwordsNoMatch: 'Passwords do not match.',
    registerError: 'Registration error. Please try again.',
    emailAlreadyExists: 'Email is already registered',
    usernameAlreadyExists: 'Username is already taken',
    invalidEmailFormat: 'Invalid email format',
    invalidUsernameFormat: 'Username must be between 3 and 20 characters and can only contain letters, numbers, hyphens and underscores',
    allFieldsRequired: 'All fields are required',
    checkEmailToVerify: 'Check your inbox: we have sent you a link to verify your account.',
    checkEmailForCode: 'We have sent a 6-digit code to your email. Enter it on the website to verify your account.',
    enterCodeHere: 'Enter the code',
    enterVerificationCode: 'Enter the code we sent you by email.',
    verificationCodeLabel: 'Verification code',
    verificationCodePlaceholder: '000000',
    verifyButton: 'Confirm',
    resendCodeButton: 'Resend the code',
    codeMustBe6Digits: 'The code must be 6 digits.',
    noCodeReceived: "Didn't receive the code?",
    andResendCode: 'Log in to request a new one.',
    verificationSuccess: 'Email verified successfully.',
    verificationCompleteMessage: 'Verification complete. You can now log in.',
    verificationAlreadyVerified: 'Your account is already verified; you can log in.',
    emailNotVerified: 'You must verify your email address to access.',
    resendVerificationLabel: 'Resend verification email:',
    resendVerificationButton: 'Resend email',
    verificationEmailSent: 'A new verification email has been sent.',
    sending: 'Sending...',
    verificationTitle: 'Email verification',
    verifying: 'Verifying...',
    verificationFailed: 'Verification failed. The link may have expired.',
    verificationAlreadyUsed: 'This link was already used. Your account is already verified; you can log in.',
    verificationTokenMissing: 'Verification link is missing.',
    goToLogin: 'Go to login',
    
    // Home
    welcomeTitle: 'The voice within the pages',
    welcomeP1: 'Here, where imagination ceases to be a whisper and becomes written word, worlds that do not yet exist are born and characters who await to be remembered breathe. This is not just a place to tell stories: it is a refuge for storytellers, a workshop for plot architects, a living archive where every idea finds form, order, and purpose.',
    welcomeP2: 'In The voice within the pages, your stories do not exist in solitude. This is a space designed for your ideas to find form, depth, and coherence, allowing you to develop stories that breathe and evolve naturally. Whether you write fantasy, science fiction, drama, or chronicles of impossible worlds, here your narratives grow, consolidate, and prepare to be shared with others, within a universe that respects and enhances your creative vision.',
    welcomeP3: 'Cross the threshold. Write. Build. Give voice to the pages.',
    
    // Profile
    profileTitle: 'My Profile',
    memberSince: 'Member since',
    profileImage: 'Profile image',
    changeProfileImage: 'Change profile image',
    clickToChangeImage: 'Click to change image',
    invalidImageType: 'Invalid file type. Only images are allowed.',
    imageTooLarge: 'Image is too large (max 2MB)',
    uploadError: 'Error uploading image',
    
    // Change Password
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    passwordChanged: 'Password updated successfully',
    passwordChangeError: 'Error changing password',
    currentPasswordIncorrect: 'Current password is incorrect',
    newPasswordsDontMatch: 'New passwords do not match',
    samePasswordError: 'New password must be different from current',
    
    // Scriptorium
    scriptoriumWelcome: 'Welcome to the Scriptorium',
    stories: 'Stories',
    storiesDescription: 'Create and manage your tales. From short stories to epic sagas, organize all your narratives in one place.',
    characters: 'Characters',
    charactersDescription: 'Bring your protagonists and antagonists to life. Define their traits, motivations, and development arcs.',
    plots: 'Timelines',
    plotsDescription: 'Manage the timelines of your stories. Organize events, plots and notes.',
    
    // Plots/Timelines Page
    timelines: 'Timelines',
    plot: 'plot',
    errorLoadingTimelines: 'Error loading timelines',
    noTimelinesYet: "You don't have any timelines yet",
    createStoryForTimeline: 'Create a story to generate a timeline',
    allStories: 'All stories',
    noTimelinesForThisStory: 'No timelines for this story',
    selectAnotherStoryOrCreate: 'Select another story or create a new timeline',
    newTimeline: 'New timeline',
    timelineName: 'Timeline name',
    timelineNamePlaceholder: 'E.g.: Main timeline',
    story: 'Story',
    selectStory: 'Select story',
    storyRequired: 'You must select a story',
    errorCreatingTimeline: 'Error creating timeline',
    confirmDeleteTimeline: 'Delete this timeline?',
    deleteTimelineConfirmMessage: 'The timeline «{name}» and all its plots will be permanently deleted. This action cannot be undone.',
    errorDeletingTimeline: 'Error deleting timeline',
    errorLoadingTimeline: 'Error loading timeline',
    timelineNotFound: 'Timeline not found',
    backToTimelines: 'Back to timelines',
    tramas: 'Plots',
    noPlotsYet: 'No plots yet',
    addPlotsToTimeline: 'Add plots to this timeline',
    chapter: 'Ch.',
    chapters: 'chapters',
    chapterSingular: 'chapter',
    addChapter: 'Add chapter',
    removeChapter: 'Remove chapter',
    newPlot: 'New plot',
    plotName: 'Plot name',
    plotNamePlaceholder: 'E.g.: Main romance',
    startChapter: 'Start chapter',
    endChapter: 'End chapter',
    plotNameRequired: 'Plot name is required',
    startCantBeGreaterThanEnd: 'Start cannot be greater than end',
    errorCreatingPlot: 'Error creating plot',
    creating: 'Creating...',
    errorUpdatingPlot: 'Error updating plot',
    plotDescription: 'Description',
    plotDescriptionPlaceholder: 'Optional plot description',
    plotColor: 'Color',
    editPlot: 'Edit plot',
    highlightOnTimeline: 'Highlight on timeline',
    savePlot: 'Save',
    confirmDeletePlot: 'Delete this plot?',
    deletePlotConfirmMessage: 'The plot «{name}» will be permanently deleted. This action cannot be undone.',
    deletePlotWarning: 'This action cannot be undone.',
    errorDeletingPlot: 'Error deleting plot',
    deleting: 'Deleting...',
    notes: 'Notes',
    note: 'note',
    newNote: 'New note',
    noteName: 'Note name',
    noteNamePlaceholder: 'E.g.: Key event',
    notePosition: 'Position (chapter)',
    noteNameRequired: 'Note name is required',
    noNotesYet: 'No notes yet',
    addNotesToTimeline: 'Add notes at a specific point',
    editNote: 'Edit note',
    confirmDeleteNote: 'Delete this note?',
    deleteNoteConfirmMessage: 'The note «{name}» will be deleted.',
    errorCreatingNote: 'Error creating note',
    errorUpdatingNote: 'Error updating note',
    errorDeletingNote: 'Error deleting note',
    
    // Stories Page
    myStories: 'My Stories',
    newStory: 'New Story',
    createNewStory: 'Create New Story',
    storyTitle: 'Title',
    storyTitlePlaceholder: 'Your story title...',
    storyContent: 'Content',
    storyContentPlaceholder: 'Write your story here...',
    visibility: 'Visibility',
    public: 'Public',
    private: 'Private',
    unlisted: 'Unlisted',
    create: 'Create',
    noStoriesYet: "You don't have any stories yet",
    createFirstStory: 'Create your first story and start writing',
    errorLoadingStories: 'Error loading stories',
    errorCreatingStory: 'Error creating story',
    errorDeletingStory: 'Error deleting story',
    confirmDelete: 'Delete story?',
    deleteStoryWarning: 'This action cannot be undone. The following will be permanently deleted:',
    delete: 'Delete',
    
    // Story Editor
    errorLoadingStory: 'Error loading story',
    editStory: 'Edit story',
    noCharactersYet: 'No characters yet',
    noChaptersYet: 'No chapters yet',
    addCharacter: 'Add character',
    newCharacter: 'New character',
    characterName: 'Name',
    characterDescription: 'Description',
    editCharacter: 'Edit character',
    confirmDeleteCharacter: 'Delete this character?',
    newChapter: 'New chapter',
    chapterTitle: 'Title',
    chapterOrder: 'Order',
    editChapter: 'Edit chapter',
    confirmDeleteChapter: 'Delete this chapter?',
    editChapterContent: 'Edit text',
    storyTextInChapters: 'Story text is written in each chapter.',
    manageChaptersAndContent: 'Manage chapters and content',
    chapterNotFound: 'Chapter not found',
    errorSavingStory: 'Error saving story',
    backToStories: 'Back to stories',
    saving: 'Saving...',
    saved: 'Saved',
    unsaved: 'Unsaved',
    untitledStory: 'Untitled story',
    settings: 'Settings',
    startWriting: 'Start writing your story...',
    words: 'words',
    chars: 'characters',
    save: 'Save',
    addSeparator: 'Add separator',
    separatorDefaultLabel: 'Separator',
    
    // Formatting Toolbar
    paragraph: 'Paragraph',
    heading: 'Heading',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    bulletList: 'Bullet list',
    numberedList: 'Numbered list',
    quote: 'Quote',
    alignLeft: 'Align left',
    alignCenter: 'Center',
    alignRight: 'Align right',
    alignJustify: 'Justify',
    
    // Common
    loading: 'Loading...',
    back: 'Back',
    cancel: 'Cancel',
    close: 'Close',
    quickAccess: 'Quick access',
    navigation: 'Navigation',
    account: 'Account',

    // Tutorial
    tutorialNext: 'Next',
    tutorialPrev: 'Previous',
    tutorialHomeScriptoriumTitle: 'Scriptorium',
    tutorialHomeScriptoriumBody: 'Your workspace. From here you access Stories, Characters and Timelines to organise your narrative projects.',
    tutorialHomeArchiveTitle: 'Archive',
    tutorialHomeArchiveBody: 'The archive will let you save and browse content. This feature is coming soon.',
    tutorialHomeMenuTitle: 'Dropdown menu',
    tutorialHomeMenuBody: 'In the top-right corner of the header you will find the menu: Home, My profile, language and theme. Use it to navigate and configure the app.',
  }
};

const LanguageContext = createContext(null);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

